# Australian Credit Approval using Support Vector Machines (SVMs) 
 
### [Statlog (Australian Credit Approval) Data Set ](https://archive.ics.uci.edu/ml/datasets/Statlog+%28Australian+Credit+Approval%29)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("Aust_Credit_Approval_Data.csv")
df.head()

      x1     x2  x3  x4  x5     x6  x7  x8  x9  x10  x11  x12   x13  target
0  22.08  11.46   2   4   4  1.585   0   0   0    1    2  100  1213       0
1  22.67   7.00   2   8   4  0.165   0   0   0    0    2  160     1       0
2  29.58   1.75   1   4   4  1.250   0   0   0    1    2  280     1       0
3  21.67  11.50   1   5   3  0.000   1   1  11    1    2    0     1       1
4  20.17   8.17   2   6   4  1.960   1   1  14    0    2   60   159       1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      690 non-null    float64
 1   x2      690 non-null    float64
 2   x3      690 non-null    int64
 3   x4      690 non-null    int64
 4   x5      690 non-null    int64
 5   x6      690 non-null    float64
 6   x7      690 non-null    int64
 7   x8      690 non-null    int64
 8   x9      690 non-null    int64
 9   x10     690 non-null    int64
 10  x11     690 non-null    int64
 11  x12     690 non-null    int64
 12  x13     690 non-null    int64
 13  target  690 non-null    int64
dtypes: float64(3), int64(11)
memory usage: 75.6 KB

In [4]:
df.describe()

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,target
count,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.000000,690.00000,690.000000,690.000000,690.000000,690.000000,690.000000
mean,31.568203,4.758725,1.766667,7.372464,4.692754,2.223406,0.523188,0.427536,2.40000,0.457971,1.928986,184.014493,1018.385507,0.444928
std,11.853273,4.978163,0.430063,3.683265,1.992316,3.346513,0.499824,0.495080,4.86294,0.498592,0.298813,172.159274,5210.102598,0.497318
min,13.750000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,22.670000,1.000000,2.000000,4.000000,4.000000,0.165000,0.000000,0.000000,0.00000,0.000000,2.000000,80.000000,1.000000,0.000000
50%,28.625000,2.750000,2.000000,8.000000,4.000000,1.000000,1.000000,0.000000,0.00000,0.000000,2.000000,160.000000,6.000000,0.000000
75%,37.707500,7.207500,2.000000,10.000000,5.000000,2.625000,1.000000,1.000000,3.00000,1.000000,2.000000,272.000000,396.500000,1.000000
max,80.250000,28.000000,3.000000,14.000000,9.000000,28.500000,1.000000,1.000000,67.00000,1.000000,3.000000,2000.000000,100001.000000,1.000000

Let's move on to machine learning. 
## Machine Learning

In [5]:
X = df.iloc[:,:-1]
y = df['target']

In [6]:
print(y)

0      0
1      0
2      0
3      1
4      1
      ..
685    1
686    0
687    1
688    1
689    1
Name: target, Length: 690, dtype: int64

In [7]:
X

        x1      x2  x3  x4  x5     x6  x7  x8  x9  x10  x11  x12   x13
0    22.08  11.460   2   4   4  1.585   0   0   0    1    2  100  1213
1    22.67   7.000   2   8   4  0.165   0   0   0    0    2  160     1
2    29.58   1.750   1   4   4  1.250   0   0   0    1    2  280     1
3    21.67  11.500   1   5   3  0.000   1   1  11    1    2    0     1
4    20.17   8.170   2   6   4  1.960   1   1  14    0    2   60   159
..     ...     ...  ..  ..  ..    ...  ..  ..  ..  ...  ...  ...   ...
685  31.57  10.500   2  14   4  6.500   1   0   0    0    2    0     1
686  20.67   0.415   2   8   4  0.125   0   0   0    0    2    0    45
687  18.83   9.540   2   6   4  0.085   1   0   0    0    2  100     1
688  27.42  14.500   2  14   8  3.085   1   1   1    0    2  120    12
689  41.00   0.040   2  10   4  0.040   0   1   1    0    1  560     1

[690 rows x 13 columns]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

### Importing and  training the Support Vector Classifier

In [15]:
from sklearn.svm import SVC

In [11]:
svm_model = SVC(kernel='linear', C=30, gamma='auto')

In [12]:
svm_model.fit(X_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [13]:
predictions = svm_model.predict(X_test)
predictions

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int64)

In [14]:
svm_model.score(X_test, y_test)

0.8502415458937198